## Load configurations
- AmcCarrierCore:
    - AxiSy56040:
        - OutputConfig: !<value>
            - RTM_TIMING_IN0
            - RTM_TIMING_IN0
            - RTM_TIMING_IN0
            - RTM_TIMING_IN1
    - AmcCarrierTiming:
        - TimingFrameRx:
            - ClkSel: !<value> 0
- AppTop:
    - AppCore:
        - MpsLinkNodeCore:
            - MpsMitigationCore:
                - mpsConfig: !<value> 0x0
